# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-appsync-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2

plugins:
   - serverless-appsync-plugin

appSync:
  name: bookstoreAppSyncAPI
  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      userPoolId: !Ref cognitoUserPool
  resolvers:
    Query.getBookById:
      functions:
        - dataSource: booksTable
          request: mapping-templates/Query.getBookById.request.vtl
          response: mapping-templates/Query.getBookById.response.vtl
    Mutation.createBook:
      functions:
        - dataSource: booksTable 
          request: mapping-templates/Mutation.createBook.request.vtl
          response: mapping-templates/Mutation.createBook.response.vtl
  dataSources:
    booksTable:
      type: AMAZON_DYNAMODB
      config:
        tableName: !Ref booksTable
resources:
 Resources:
  ${file(resources.yml)}
